In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import AdaBoostClassifier

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
# loading the data from csv file to a Pandas DataFrame
parkinsons_data = pd.read_csv('/content/drive/MyDrive/Multiple diseases prediction system /parkinsons.csv')

In [9]:
# printing the first 5 rows of the dataframe
parkinsons_data.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.813031,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.00000,20.651,1,0.429895,0.825288,-4.813031,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.00000,20.644,1,0.434969,0.845379,-4.813031,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.00000,19.649,1,0.417356,0.845379,-4.813031,0.234513,2.332180,0.410335

In [10]:
# number of rows and columns in the dataframe
parkinsons_data.shape

(8223, 24)

In [11]:
# getting more information about the dataset
parkinsons_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8223 entries, 0 to 8222
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              8223 non-null   object
 1   MDVP:Fo(Hz)       8223 non-null   float64
 2   MDVP:Fhi(Hz)      8223 non-null   float64
 3   MDVP:Flo(Hz)      8223 non-null   float64
 4   MDVP:Jitter(%)    8223 non-null   float64
 5   MDVP:Jitter(Abs)  8223 non-null   float64
 6   MDVP:RAP          8223 non-null   float64
 7   MDVP:PPQ          8223 non-null   float64
 8   Jitter:DDP        8223 non-null   float64
 9   MDVP:Shimmer      8223 non-null   float64
 10  MDVP:Shimmer(dB)  8223 non-null   float64
 11  Shimmer:APQ3      8223 non-null   float64
 12  Shimmer:APQ5      8223 non-null   float64
 13  MDVP:APQ          8223 non-null   float64
 14  Shimmer:DDA       8223 non-null   float64
 15  NHR               8223 non-null   float64
 16  HNR               8223 non-null   float64
 17  status            8223 non-null   int64
 18  RPDE              8223 non-null   float64
 19  DFA               8223 non-null   float64
 20  spread1           8223 non-null   float64
 21  spread2           8223 non-null   float64
 22  D2                8223 non-null   float64
 23  PPE               8223 non-null   float64
dtypes: float64(22), int64(1), object(1)
memory usage: 1.5+ MB

In [12]:
# checking for missing values in each column
parkinsons_data.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [13]:
# getting some statistical measures about the data
parkinsons_data.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,...,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000,8223.000000
mean,2713.140740,193.540847,115.108255,0.014301,0.000043,0.284334,0.015445,0.565303,0.018633,0.280428,...,0.049998,0.022597,21.595973,0.762982,0.503349,0.751784,-5.718488,-0.072122,1.990103,0.205714
std,9033.320712,89.886232,43.064498,0.052139,0.000034,1.565576,1.091708,50.363387,0.020584,0.195021,...,0.035413,0.038473,4.688580,0.425279,0.102418,0.073744,1.099634,1.310305,1.811680,0.088115
min,88.333000,102.145000,65.476000,0.001680,0.000000,0.000680,0.000920,0.002040,0.000000,0.085000,...,0.013640,0.000000,8.441000,0.000000,0.256570,0.574282,-7.964984,-7.964984,-7.964984,0.044539
25%,117.274000,131.897000,82.764000,0.003390,0.000020,0.001710,0.001940,0.005040,0.000000,0.149000,...,0.024870,0.004950,19.055000,1.000000,0.427785,0.686579,-6.482096,0.158266,2.058658,0.136390
50%,148.790000,172.860000,102.874000,0.004940,0.000040,0.002260,0.002630,0.007420,0.016080,0.216000,...,0.038670,0.010490,22.219000,1.000000,0.502380,0.743937,-5.736781,0.210279,2.344876,0.199889
75%,197.569000,219.290000,135.041000,0.007420,0.000050,0.003725,0.003900,0.011680,0.027190,0.350000,...,0.063210,0.022200,25.032000,1.000000,0.596040,0.845379,-4.960234,0.269866,2.631793,0.249703
max,34567.000000,592.030000,239.170000,0.345678,0.000260,9.000000,99.000000,4567.000000,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.845379,-2.434031,0.450493,3.671155,0.527367

In [14]:
# distribution of target Variable
parkinsons_data['status'].value_counts()

status
1    6274
0    1949
Name: count, dtype: int64

In [15]:
parkinsons_data = parkinsons_data.select_dtypes(include=['int64', 'float64'])
parkinsons_data.groupby('status').mean()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
status,,,,,,,,,,,,,,,,,,,,,
0,2718.575090,217.248181,142.693662,0.012281,0.000024,0.237406,0.002145,0.006001,0.011323,0.163199,...,0.013395,0.032046,0.010624,24.185711,0.449681,0.738083,-6.716060,-0.198728,1.707281,0.127770
1,2711.452574,186.176232,106.538927,0.014928,0.000048,0.298912,0.019576,0.739048,0.020904,0.316846,...,0.026979,0.055575,0.026317,20.791478,0.520021,0.756039,-5.408595,-0.032791,2.077961,0.229927

In [16]:
print(parkinsons_data.columns)

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')

In [17]:
X = parkinsons_data.drop(columns=['status'], axis=1)
Y = parkinsons_data['status']

In [18]:
print(X)

      MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0         119.992       157.302        74.997         0.00784
1         122.400       148.650       113.819         0.00968
2         116.682       131.111       111.555         0.01050
3         116.676       137.871       111.366         0.00997
4         116.014       141.781       110.655         0.01284
...           ...           ...           ...             ...
8218      150.440       163.441       144.736         0.00396
8219      148.462       161.078       141.998         0.00397
8220      149.818       163.417       144.786         0.00336
8221      117.226       123.925       106.656         0.00417
8222      116.848       217.552        99.503         0.00531

      MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0              0.00007   0.00370   0.00554     0.01109       0.04374
1              0.00008   0.00465   0.00696     0.01394       0.06134
2              0.00009   0.00544   0.00781     0.01633       0.05233
3              0.00009   0.00502   0.00698     0.01505       0.05492
4              0.00011   0.00655   0.00908     0.01966       0.06425
...                ...       ...       ...         ...           ...
8218           0.00003   0.00206   0.00233     0.00619       0.02551
8219           0.00003   0.00202   0.00235     0.00605       0.01831
8220           0.00002   0.00174   0.00198     0.00521       0.02145
8221           0.00004   0.00186   0.00270     0.00558       0.01909
8222           0.00005   0.00260   0.00346     0.00780       0.01795

      MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE  \
0                0.426  ...   0.02971      0.06545  0.02211  21.033  0.414783
1                0.626  ...   0.04368      0.09403  0.01929  19.085  0.458359
2                0.482  ...   0.03590      0.08270  0.00000  20.651  0.429895
3                0.517  ...   0.03772      0.08771  0.00000  20.644  0.434969
4                0.584  ...   0.04465      0.10470  0.00000  19.649  0.417356
...                ...  ...       ...          ...      ...     ...       ...
8218             0.237  ...   0.02148      0.03964  0.00611  23.133  0.352396
8219             0.163  ...   0.01559      0.02849  0.00639  22.866  0.408598
8220             0.198  ...   0.01666      0.03464  0.00595  23.008  0.329577
8221             0.171  ...   0.01949      0.02592  0.00955  23.079  0.603515
8222             0.163  ...   0.01756      0.02429  0.01179  22.085  0.663842

           DFA   spread1   spread2        D2       PPE
0     0.815285 -4.813031  0.266482  2.301442  0.284654
1     0.819521 -4.813031  0.335590  2.486855  0.368674
2     0.825288 -4.813031  0.311173  2.342259  0.332634
3     0.845379 -4.813031  0.334147  2.405554  0.368975
4     0.845379 -4.813031  0.234513  2.332180  0.410335
...        ...       ...       ...       ...       ...
8218  0.759320 -6.261446  0.183218  2.264226  0.144105
8219  0.768845 -5.704053  0.216204  2.679185  0.197710
8220  0.757180 -6.277170  0.109397  2.209021  0.156368
8221  0.669565 -5.619070  0.191576  2.027228  0.215724
8222  0.656516 -5.198864  0.206768  2.120412  0.252404

[8223 rows x 22 columns]

In [19]:
print(Y)

0       1
1       1
2       1
3       1
4       1
       ..
8218    1
8219    1
8220    1
8221    0
8222    0
Name: status, Length: 8223, dtype: int64

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [21]:
print(X.shape, X_train.shape, X_test.shape)

(8223, 22) (6578, 22) (1645, 22)

In [22]:
# Initialize the AdaBoost model
model = AdaBoostClassifier(random_state=42)

In [23]:
# Training the AdaBoost model with training data
model.fit(X_train, Y_train)

AdaBoostClassifier(random_state=42)

In [24]:
# Accuracy score on training data
adaboost_training_data_accuracy = accuracy_score(Y_train, model.predict(X_train))
print('AdaBoost Accuracy score on training data:', adaboost_training_data_accuracy)

AdaBoost Accuracy score on training data: 0.9612344177561569

In [25]:
# Accuracy score on test data
adaboost_test_data_accuracy = accuracy_score(Y_test, model.predict(X_test))
print('AdaBoost Accuracy score on test data:', adaboost_test_data_accuracy)

AdaBoost Accuracy score on test data: 0.956838905775076

In [26]:
input_data = (140.341,159.774,67.021,0.00817,0.00001,0.0043,0.0044,0.01289,0.03198,0.313,0.0183,0.0181,0.02428,0.0549,0.02183,19.57,0.537264,0.720908,-5.40942,0.22685,2.359973,0.226156)

# changing input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)


if (prediction[0] == 0):
  print("The Person does not have Parkinsons Disease")

else:
  print("The Person has Parkinsons")

[1]
The Person has Parkinsons

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(

In [27]:
import pickle

In [28]:
filename = 'parkinsons_prediction_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [29]:
# loading the saved model
loaded_model = pickle.load(open('parkinsons_prediction_model.sav', 'rb'))

In [30]:
for column in X.columns:
  print(column)

MDVP:Fo(Hz)
MDVP:Fhi(Hz)
MDVP:Flo(Hz)
MDVP:Jitter(%)
MDVP:Jitter(Abs)
MDVP:RAP
MDVP:PPQ
Jitter:DDP
MDVP:Shimmer
MDVP:Shimmer(dB)
Shimmer:APQ3
Shimmer:APQ5
MDVP:APQ
Shimmer:DDA
NHR
HNR
RPDE
DFA
spread1
spread2
D2
PPE